### ISSUE TITLE
Add keys to planner

### ISSUE THREAD

**Issue by lotu** [ccplanner/planner#1]
Planner needs to handle keys and locks.  Red, Blue, and Yellow keys are used up when opening a lock, Green Keys are not.

**Comment by alexmemory** [comment]
I committed something for this, but it does not work at all (fast downward says no solution found) and it slows down the system pretty well too.  :-)  Will need to investigate this further.

**Comment by lotu** [comment]
I see the problem, Fast Downward does find a solution of first tick, but after chip picks up the key it can't find a solution any more.  The cause of this is that the inventory is not translated to the initial state.

**Comment by lotu** [comment]
My lattest caching agent, solves the key levels correctly.  It does this by recording all the moves and then playing them back.

**Comment by alexmemory** [comment]
I'm confused; is caching a temporary solution or can we use it permanently?  I also don't understand how/if FD solves the keys level with 1 green key and 2 green doors. Hmmm.

**Comment by lotu** [comment]
Caching the solution covers up the problem but does not eliminate it.  It still could become a problem in the future in which case it would be much less obvious.

**Comment by alexmemory** [comment]
The 1GK 2GD level now fails (correctly, since the PDDL isn't yet able to handle the special case of green doors)

**Comment by lotu** [comment]
I added "key mess" a classical level, with keys that we solve currently.  Also a solution to the current problem might be to make a separate action for green doors that doesn't subtract a key.

**Comment by alexmemory** [comment]
Keys and key mess now run correctly.  The problem with the when clause was a simple syntax thing - you need to AND the effects.  Pretty obvious.

**Comment by alexmemory** [comment]
And LESSON 1 from cc-ms works.

**Comment by lotu** [comment]
Sweet job!!!
